name:                polysemy-recusion
version:             0.1.0.0
github:              "ShapeOfMatter/polysemy-recusion"
license:             BSD3
author:              "Mako Bates"
maintainer:          "example@example.com"
copyright:           "2021 Mako Bates"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ShapeOfMatter/polysemy-recusion#readme>

ghc-options: 
    - "-fplugin=Polysemy.Plugin"
    - "-Wall"
#    - "-O2"

default-extensions:
    - DataKinds
    - FlexibleContexts
    - GADTs
    - LambdaCase
    - PolyKinds
    - RankNTypes
    - ScopedTypeVariables
    - TemplateHaskell
    - TypeApplications
    - TypeOperators
    - TypeFamilies

dependencies:
- base >= 4.7 && < 5
- polysemy >= 1.4  
- polysemy-plugin >= 0.3

library:
  source-dirs: src

executables:
  polysemy-recusion-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - polysemy-recusion

tests:
  polysemy-recusion-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - polysemy-recusion
